# Generated by Django 4.0.2 on 2022-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventstatus_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='event_status',
            field=models.CharField(choices=[('0', 'canceled'), ('1', 'new event'), ('2', 'in progress'), ('3', 'finished')], max_length=30),
        ),
    ]
